from dataclasses import dataclass


@dataclass
class DotsNames():
    BASHRC = "bashrc"
    BASH_PROFILE = "bash-profile"
    DUNST_CONFIG_DWM = "dunst-config"
    ALACRITTY_CONFIG = "alacritty-config"
    BTOP_CONFIG = "btop-config"
    ROFI_CONFIG = "rofi-config"
    RANGER_CONFIG = "ranger-config"
    DWM_CONFIG = "dwm-config"
    PLSTATUS_CONFIG = "plstatus-config"
    ENHANCER_FOR_YOUTUBE_CONFIG = "enhancer-for-youtube-config"
    REFLECTOR_CONFIG = "reflector-config"
    HYPRLAND_CONFIG = "hyprland-config"
    HYPRPAPER_CONFIG = "hyprpaper-config"
    FUZZEL_CONFIG = "fuzzel-config"
    WAYBAR_CONFIG = "waybar-config"
    WAYBAR_STYLE = "waybar-style"
    FIREFOX_USERCHROME = "firefox-userchrome"
    TMUX_CONFIG = "tmux-config"
    SWAYLOCK_CONFIG = "swaylock-config"
    BATTERY_NOTIFIER_SERVICE = "battery-notifier-service"
    DOAS_CONFIG = "doas-config"
    MICRO_BINDINGS = "micro-bindings"
    MICRO_CONFIG = "micro-config"
    NANO_CONFIG = "nano-config"
    SUDOEDIT = "sudoedit"
    DASH_SH_HOOK = "dash-sh-hook"
    QTILE_CONFIG = "qtile-config"
    DWM_STARTUP = "dwm-startup"
    QTILE_STARTUP = "qtile-startup"
    BASHRC_DEVICE = "bashrc-device"
    BASH_PROFILE_DEVICE = "bash-profile-device"
    HYPRLAND_CONFIG_DEVICE = "hyprland-config-device"
    QTILE_CONFIG_DEVICE = "qtile-config-device"
    XLOCK = "xlock"
    START_X_WM = "start-x-wm"
    ALACRITTY_START_SCRIPT = "alacritty-start-script"
    UPDATE_SCRIPT = "update-script"
    BATTER_GRAPH_TILE = "battery-graph-qtile"
    QTILE_MONADTALL_LAYOUT_ICON = "qtile-monadtall-layout-icon"
    QTILE_MAX_LAYOUT_ICON = "qtile-max-layout-icon"
    GDIFF_SCRIPT = "gdiff-script"
    EXTRACT_SCRIPT = "extract-script"
    FISH_CONFIG = "fish-config"
    PFETCH_CUSTOM_LOGOS = "pfetch-custom-logos"
    PFETCH_CONFIG = "pfetch-config"
    ALIAS_RS_CONFIG = "alias-rs-config"
    ALIAS_RS_CONFIG_DEVICE = "alias-rs-config-device"
    PARU_CONFIG = "paru-config"
    PIKAUR_CONFIG = "pikaur-config"
    VSCODE_KEYBINDINGS = "vscode-keybindings"
