BASHRC="bashrc"
BASH_PROFILE="bash-profile"
DUNST_CONFIG_DWM="dunst-config-dwm"
DUNST_CONFIG_HYPRLAND="dunst-config-hyprland"
DUNST_CONFIG_QTILE="dunst-config-qtile"
ALACRITTY_CONFIG="alacritty-config"
BTOP_CONFIG="btop-config"
ROFI_CONFIG="rofi-config"
RANGER_CONFIG="ranger-config"
DWM_CONFIG="dwm-config"
PLSTATUS_CONFIG="plstatus-config"
ENHANCER_FOR_YOUTUBE_CONFIG="enhancer-for-youtube-config"
REFLECTOR_CONFIG="reflector-config"
HYPRLAND_CONFIG="hyprland-config"
HYPRPAPER_CONFIG="hyprpaper-config"
FUZZEL_CONFIG="fuzzel-config"
WAYBAR_CONFIG="waybar-config"
WAYBAR_STYLE="waybar-style"
FOOT_CONFIG="foot-config"
FIREFOX_USERCHROME="firefox-userchrome"
TMUX_CONFIG="tmux-config"
SWAYLOCK_CONFIG="swaylock-config"
BATTERY_NOTIFIER_SERVICE="battery-notifier-service"
DOAS_CONFIG="doas-config"
MICRO_BINDINGS="micro-bindings"
MICRO_CONFIG="micro-config"
NANO_CONFIG="nano-config"
SUDOEDIT="sudoedit"
DASH_SH_HOOK="dash-sh-hook"
QTILE_CONFIG="qtile-config"
DWM_STARTUP="dwm-startup"
QTILE_STARTUP="qtile-startup"
BASHRC_DEVICE="bashrc-device"
BASH_PROFILE_DEVICE="bash-profile-device"
HYPRLAND_CONFIG_DEVICE="hyprland-config-device"
QTILE_CONFIG_DEVICE="qtile-config-device"
XLOCK="xlock"
START_X_WM="start-x-wm"
ALACRITTY_START_SCRIPT="alacritty-start-script"
ARCH_UPDATE_CHECKER="arch-update-checker"
UPDATE_SCRIPT="update-script"
BATTER_GRAPH_TILE="battery-graph-qtile"

DOTS_NAMES = [
    BASHRC,
    BASH_PROFILE,
    DUNST_CONFIG_DWM,
    DUNST_CONFIG_HYPRLAND,
    DUNST_CONFIG_QTILE,
    ALACRITTY_CONFIG,
    BTOP_CONFIG,
    ROFI_CONFIG,
    RANGER_CONFIG,
    DWM_CONFIG,
    PLSTATUS_CONFIG,
    ENHANCER_FOR_YOUTUBE_CONFIG,
    REFLECTOR_CONFIG,
    HYPRLAND_CONFIG,
    HYPRPAPER_CONFIG,
    FUZZEL_CONFIG,
    WAYBAR_CONFIG,
    WAYBAR_STYLE,
    FOOT_CONFIG,
    FIREFOX_USERCHROME,
    TMUX_CONFIG,
    SWAYLOCK_CONFIG,
    BATTERY_NOTIFIER_SERVICE,
    DOAS_CONFIG,
    MICRO_BINDINGS,
    MICRO_CONFIG,
    NANO_CONFIG,
    SUDOEDIT,
    DASH_SH_HOOK,
    QTILE_CONFIG,
    DWM_STARTUP,
    QTILE_STARTUP,
    BASHRC_DEVICE,
    BASH_PROFILE_DEVICE,
    HYPRLAND_CONFIG_DEVICE,
    QTILE_CONFIG_DEVICE,
    XLOCK,
    START_X_WM,
    ALACRITTY_START_SCRIPT,
    ARCH_UPDATE_CHECKER,
    UPDATE_SCRIPT,
    BATTER_GRAPH_TILE
]
