CONFIG_SUBSTITUTIONS = "substitutions"
EXPANDED_SUBSTITUTIONS = "setup-expanded-substitutions"
MAIN_COLOR = "main-color"
SECONDARY_COLOR = "secondary-color"
PRESET = "preset"
DOTFILES_LITE_MODE_KEY = "dotfiles-lite-mode"
